### ISSUE TITLE
How does the YAML Mapping work?

### ISSUE THREAD

**Issue by jangaehler** [fre5h/DoctrineEnumBundle#117]
I'm using YAML instead of Annotations for ORM Mapping. I've tried to translate the Annotations like this:

```
status_delivery:
        type: StatusDeliveryType
```
but this does not work. The SQL result looks like this:

```
… status_delivery VARCHAR(255) CHECK(status_delivery IN ()) NOT NULL, 
… EXEC sp_addextendedproperty N'MS_Description', N'(DC2Type:StatusDeliveryType)',
 N'SCHEMA', dbo, N'TABLE', foobar, N'COLUMN', status_delivery;
```
I know, I'm missing this part:

```
use Fresh\DoctrineEnumBundle\Validator\Constraints as DoctrineAssert; … 
* @DoctrineAssert\Enum(entity="App\DBAL\Types\BasketballPositionType") 
```

But how do I write this in YAML?

**Comment by fre5h** [comment]
@jangaehler Have you registered your enum type in doctrine.yaml configuration?

**Comment by fre5h** [comment]
What database do you use?

**Comment by jangaehler** [comment]
I have registered my enum type in config.yml.

```
doctrine:
    dbal:
        types:
              StatusDeliveryType: ACME\CoreBundle\DBAL\Types\StatusDeliveryType
```

I'm using MSSQL(Azure DB).
