### ISSUE TITLE
Invalid value "" for ENUM

### ISSUE THREAD

**Issue by TZK-** [fre5h/DoctrineEnumBundle#173]
I have an error when trying to set a value in my entity which is not part of my enum.
In my entity, I set a validation constraint to ensure that values must one of the enum.

Howewer, It always throws InvalidArgumentException when it calls AbstractEnumType::convertToDatabaseValue() after I try to insert a new record in my database with a value which is not in the enum.

I do not really understand why convertToDatabaseValue() method throws an exception in this case since I want the validation constraint being called first.

Am I doing something wrong ?

```php
declare(strict_types=1);

namespace App;

class Permission
{
    /**
     * @ORM\Id()
     * @ORM\Column(type="uuid", unique=true)
     *
     * @Assert\Uuid
     *
     * @var string
     */
    private $id;

    /**
     * @ORM\Column(length=255, nullable=false, type="security_permission")
     *
     * @Assert\Length(max=255)
     * @DoctrineAssert\Enum(entity="App\PermissionEnum")
     *
     *
     * @var string
     */
    private string $name;
```

```php
<?php

declare(strict_types=1);

namespace App;

use Fresh\DoctrineEnumBundle\DBAL\Types\AbstractEnumType;

final class PermissionEnum extends AbstractEnumType
{
    public const VIEW = 'view';
    public const CREATE = 'create';

    protected static $choices = [
        self::VIEW => self::VIEW,
        self::CREATE => self::CREATE
    ];
}
```

**Comment by fre5h** [comment]
Have you added the next line into your entity?

```php
use Fresh\DoctrineEnumBundle\Validator\Constraints as DoctrineAssert;
```

I see it is missed in your example. But maybe you deleted it to make your code snippet shorter. Anyway I need to clarify, that you don't forget to include this validation constraint for you entity.

**Comment by TZK-** [comment]
Indeed, I have correctly imported the right constraint and missed to add it in my previous post after cleaning up a little bit my entity. (I edited the previous message to include the missing parts)

**Comment by fre5h** [comment]
Please add config for Doctrine in your project

**Comment by TZK-** [comment]
```yaml
# config/packages/doctrine.yaml
doctrine:
    dbal:
        types:
            security_permission: App\PermissionEnum
    orm:
        auto_generate_proxy_classes: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
                
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
```

The type is working well when bound to my entity field since it generate a good SQL migration.
