### ISSUE TITLE
Issues with types naming in YAML configuration after upgrade to v9.0

### ISSUE THREAD

**Issue by mzurawek** [fre5h/DoctrineEnumBundle#222]
When upgrading bundle (v8.1.2 -> v9.0.0) I had to change configuration in doctrine.yaml.

Before:
```
doctrine:
    dbal:
       types:
         BasketballPositionType: App\DBAL\Types\BasketballPositionType

```
This produced error: `Unknown type BasketballPositionType`

What finally worked (full class path instead of just class name):
```
doctrine:
    dbal:
       types:
         App\DBAL\Types\BasketballPositionType: App\DBAL\Types\BasketballPositionType
```

How entity looks like:
```
#[ORM\Entity(repositoryClass: FooRepository::class)]
class Foo
{
    #[ORM\Column(type: BasketballPositionType::class, nullable: false)]
    #[DoctrineAssert\EnumType(entity: BasketballPositionType::class)]
    private string $basketballPositionType;
}
```

**Comment by fre5h** [comment]
@mzurawek I tried to reproduce, but cannot. Check the comment for this column in DB. Should be '(DC2Type:BasketballPositionType)'

**Comment by mzurawek** [comment]
Yes, there is the right comment.

I've done the clean install of Symfony 6.1, done configuration according to:
https://github.com/fre5h/DoctrineEnumBundle/blob/main/Resources/docs/usage_example.md
And even when starting `php bin/console make:migration` I've got:
In Exception.php line 120:
```                                                                                                                                                                                                                                                                                                               
Unknown column type "App\DBAL\Types\BasketballPositionType" requested. Any Doctrine type that you use has to be registered with \Doctrine\DBAL\Types\Type::addType(). You can get a list of all the known types with \Doctrine\DBAL\Types\Type::getTypesMap(). If this error occurs during database introspection t  
  hen you might have forgotten to register all database types for a Doctrine Type. Use AbstractPlatform#registerDoctrineTypeMapping() or have your custom types implement Type#getMappedDatabaseTypes(). If the type name is empty you might have a problem with the cache or forgot some mapping information.
```

Changing doctrine.yaml configuration to:
```
doctrine:
    dbal:
       types:
            App\DBAL\Types\BasketballPositionType: App\DBAL\Types\BasketballPositionType
```
solves the issue, but the comment on the field generated by migration is: (DC2Type:App\DBAL\Types\BasketballPositionType) - I assume it's not the desired solution.

I can provide you with this clean starting template but I'm not sure how to do that here. I'm running PHP 8.1.7

**Comment by dehy** [comment]
I have the same problem: Using `#[ORM\Column(type: BasketballPositionType::class, nullable: false)]` as documentation says, it does not work.
Using `#[ORM\Column(type: "BasketballPositionType", nullable: false)]` works.

v9.0.3

**Comment by fre5h** [comment]
Found the cause. The error was in docs example. I've updated the doc. So now the correct syntax is 
```yaml
doctrine:
  dbal:
    types:
      BasketballPositionType: App\DBAL\Types\BasketballPositionType
```
```php
#[ORM\Column(type: 'BasketballPositionType')]
#[DoctrineAssert\EnumType(entity: BasketballPositionType::class)]
private $position;
```

Alternatively you can use next:
```yaml
doctrine:
  dbal:
    types:
      App\DBAL\Types\BasketballPositionType: App\DBAL\Types\BasketballPositionType
```
```php
#[ORM\Column(type: BasketballPositionType::class)]
#[DoctrineAssert\EnumType(entity: BasketballPositionType::class)]
private $position;
```
