### ISSUE TITLE
schema:update doesn't work after database creation

### ISSUE THREAD

**Issue by jcornide** [fre5h/DoctrineEnumBundle#27]
Hi,
I'm using the bundle and it's great, but I think I found a problem.
If I run doctrine:schema:update I get this error:
[Doctrine\DBAL\DBALException]
  Unknown column type "VehicleStateType" requested. Any Doctrine type that you use has to be registered with \Doctrine\DBAL\Types\Type::addType(). You can get a list of all the known types with \Doct
  rine\DBAL\Types\Type::getTypesMap(). If this error occurs during database introspection then you might have forgot to register all database types for a Doctrine Type. Use AbstractPlatform#registerD
  octrineTypeMapping() or have your custom types implement Type#getMappedDatabaseTypes(). If the type name is empty you might have a problem with the cache or forgot some mapping information.

Is there anything else that needs to be added in oder for this to work?

**Comment by fre5h** [comment]
Hi. Did you register your new data type like in example?

```yaml
# Doctrine Configuration
doctrine:
    dbal:
        types:
            BasketballPositionType: AppBundle\DBAL\Types\BasketballPositionType
```

**Comment by jcornide** [comment]
Hi,

Yes I did:
```yaml
doctrine:
    dbal:
        types:
            vehiclestate: CoreBundle\Doctrine\DBAL\Types\VehicleStateType
```

**Comment by fre5h** [comment]
please show me annotations to the field of your entity which has `vehiclestate` type

**Comment by fre5h** [comment]
and also what version of Symfony do you use?

**Comment by jcornide** [comment]
Thanks for your time :)
```yaml
vehicle_state:
            column: vehicle_state
            type: vehiclestate
            nullable: false
```

**Comment by fre5h** [comment]
It didn't work from the beginnings?
Or only after some change? If yes then what did you change?

**Comment by fre5h** [comment]
@jcornide 
I found the cause.
As documentation says.

```yaml
# Doctrine Configuration
doctrine:
    dbal:
        types:
            BasketballPositionType: AppBundle\DBAL\Types\BasketballPositionType
```

And then you should use the type with exact name `BasketballPositionType`

```php
/** @ORM\Column(name="position", type="BasketballPositionType", nullable=true) */
protected $position;
```

In your example you have a type with name `vehiclestate` but error is for type with name `VehicleStateType`. As you see they are different. Looks like you created at first type `VehicleStateType` then created a schema, then change name to `vehiclestate` and tried to update a schema.
But Doctrine keeps the custom types as comments to the column. And there you already have a comment `DC2Type:VehicleStateType` but Doctrine cannot find this type in the configuration. You should fix it manually, because updating columns with ENUM fields has problems (as I described at the end of docs)
