### ISSUE TITLE
Unknown database type enum requested after moving from PG to MySQL

### ISSUE THREAD

**Issue by leobelen** [fre5h/DoctrineEnumBundle#29]
Hi, I was trying to move from Postgresql to Mysql and I found a weird thing: I can run the doctrine:schema:update --force command but only on a empty database. Once that succeeds, I cannot longer run it, failing with [Doctrine\DBAL\DBALException]
  Unknown database type enum requested, Doctrine\DBAL\Platforms\MySqlPlatform
   may not support it. 

Is there anything I can do to solve it?
Thanks in advance.

**Comment by fre5h** [comment]
What version of MySQL do you use?

**Comment by leobelen** [comment]
mysql  Ver 15.1 Distrib 10.0.21-MariaDB, for osx10.11 (x86_64) using readline 5.1....

**Comment by fre5h** [comment]
I didn't test it with MariaDB (As I know it is compatible with MySQL). Your version of MariaDB 10.0.21 is compatible with MySQL 5.6 which I have already used and haven't any issues.
Looks like it is a bug in Doctrine.
To enable the bundle two things should be done.
In the config you should have 
```yaml
doctrine:
    dbal:
        mapping_types:
            enum: string
        types:
            BasketballPositionType: AppBundle\DBAL\Types\BasketballPositionType
```
And comment to the related column in some table of your database should be `(DC2Type:BasketballPositionType)`. This comment is automatically added when you create the column first time via `doctrine:migrations:diff`. If comment still exists then `doctrine:schema:update --force` should have no effect on it. If you need to change the type of column you have to do it manually, because now I cannot hook into the `migration:diff` of `schema:update` commands.
