### ISSUE TITLE
Enum types in plugin bundles without declare in app/config.yml

### ISSUE THREAD

**Issue by Dm3Ch** [fre5h/DoctrineEnumBundle#69]
Hello, I'm writing an application where user could connect own plugins. Every plugin is a bundle. 
I'd like to give plugins's authors ability to use Enums, but it is not possible to add every type to app/config.yml.
 Is there any way to declare user types without writing them into app/config.yml?

**Comment by fre5h** [comment]
Your application is written on Symfony and uses Doctrine?

**Comment by Dm3Ch** [comment]
Yes

**Comment by Dm3Ch** [comment]
Is there any way to declare enum types in bundle config?

**Comment by fre5h** [comment]
Looks at this part of config

```yaml
# Doctrine Configuration
doctrine:
    dbal:
        driver:         "%database_driver%"
        host:           "%database_host%"
        port:           "%database_port%"
        dbname:         "%database_name%"
        user:           "%database_user%"
        password:       "%database_password%"
        server_version: "%database_server_version%"
        mapping_types:
            enum: string
        types:
            GameVictoryType: AppBundle\DBAL\Types\GameVictoryType
            PlayerAwardType: AppBundle\DBAL\Types\PlayerAwardType
```

If you have some custom types for Doctrine, you have to tell Doctrine what are them and where they are placed. If you want to load types from other places, not from origin Doctrine config, then you have to find the way how to hook into Doctrine and load custom types.
Right now I don't know if it is possible. I'll take a look, but it seems to me that it is not possible.

**Comment by fre5h** [comment]
Looks like I have found something useful. Checking it...

**Comment by Dm3Ch** [comment]
Thank you for helping me.

I also found some way to make what I want and checking it.

P.S. Sorry for my dab English. :)

**Comment by fre5h** [comment]
@Dm3Ch I found a solution.

Let's continue my previous example. The solution is next.

1) Remove types from config, but keep `mapping_types` section.

```yaml
# Doctrine Configuration
doctrine:
    dbal:
        driver:         "%database_driver%"
        host:           "%database_host%"
        port:           "%database_port%"
        dbname:         "%database_name%"
        user:           "%database_user%"
        password:       "%database_password%"
        server_version: "%database_server_version%"
        mapping_types:
            enum: string
```

2) Your `AppBundle` should contain next code

```php
namespace AppBundle;

use AppBundle\DBAL\Types\GameVictoryType;
use AppBundle\DBAL\Types\PlayerAwardType;
use Symfony\Component\HttpKernel\Bundle\Bundle;
use Doctrine\DBAL\Types\Type;

/**
 * AppBundle.
 *
 * @author Artem Genvald <genvaldartem@gmail.com>
 */
class AppBundle extends Bundle
{
    public function boot()
    {
        $databasePlatform = $this->container->get('doctrine.dbal.default_connection')->getDatabasePlatform();

        Type::addType('GameVictoryType', GameVictoryType::class);
        Type::addType('PlayerAwardType', PlayerAwardType::class);

        $databasePlatform->registerDoctrineTypeMapping('GameVictoryType', 'GameVictoryType');
        $databasePlatform->registerDoctrineTypeMapping('PlayerAwardType', 'PlayerAwardType');
    }

}
```

3) That's all. Enjoy.

P.S. Maybe it is also possible to register automatically the `enum` mapping type. Need to investigate it.

**Comment by fre5h** [comment]
Update

Just add to the bundle boot method this check

```php
if (!$databasePlatform->hasDoctrineTypeMappingFor('enum')) {
    $databasePlatform->registerDoctrineTypeMapping('enum', 'string');
}
```

And after that you can remove `mapping_types` section from config. But if you have other registered types, then you should keep them, you can just remove `enum: string` mapping.

```yaml
doctrine:
    dbal:
        driver:         "%database_driver%"
        host:           "%database_host%"
        port:           "%database_port%"
        dbname:         "%database_name%"
        user:           "%database_user%"
        password:       "%database_password%"
        server_version: "%database_server_version%"
#        mapping_types:
#            enum: string
```

That should solve your problem.
