### ISSUE TITLE
Compiler pass for "doctrine.dbal.default_connection"

### ISSUE THREAD

**Issue by Arthurhall** [fre5h/DoctrineEnumBundle#81]
https://github.com/fre5h/DoctrineEnumBundle/blob/master/FreshDoctrineEnumBundle.php#L29

This should be in a Compiler Pass, right ? 

Because i get the error : 
`You have requested a non-existent service "doctrine.dbal.default_connection".`

**Comment by fre5h** [comment]
Do you have DoctrineBundle in your project? Is it enabled in AppKernel?
If yes - what version of Doctrine do you use?

**Comment by Arthurhall** [comment]
Hi,

I have : 

```json
        "symfony/symfony": "3.1.*",
        "doctrine/orm": "^2.5",
        "doctrine/doctrine-bundle": "^1.6",
```

**Comment by fre5h** [comment]
What is the sequence of bundles in AppKernel? Does DoctrineEnumBundle is under the DoctrineBundle?

**Comment by Arthurhall** [comment]
yes 

```php
$bundles = [
            new Symfony\Bundle\FrameworkBundle\FrameworkBundle(),
            new Symfony\Bundle\SecurityBundle\SecurityBundle(),
            new Symfony\Bundle\TwigBundle\TwigBundle(),
            new Symfony\Bundle\MonologBundle\MonologBundle(),
            new Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle(),
            new Doctrine\Bundle\DoctrineBundle\DoctrineBundle(),
            new Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle(),
            new AppBundle\AppBundle(),
            new Retail\DoctrineBundle\RetailDoctrineBundle(),
            new Mopa\Bundle\BootstrapBundle\MopaBootstrapBundle(),
            new Symfony\Bundle\AsseticBundle\AsseticBundle(),
            new Knp\Bundle\MenuBundle\KnpMenuBundle(),
            new Lexik\Bundle\FormFilterBundle\LexikFormFilterBundle(),
            new Stof\DoctrineExtensionsBundle\StofDoctrineExtensionsBundle(),
            new FOS\JsRoutingBundle\FOSJsRoutingBundle(),
            new Fresh\DoctrineEnumBundle\FreshDoctrineEnumBundle(),
        ];
```

**Comment by Arthurhall** [comment]
I have multiple connections in my project : 

```yml
doctrine:
    dbal:
        types:
            enum_platform: AppBundle\DBAL\Types\PlatformType
        default_connection: survey 
        connections:
            survey:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
                server_version: '5.5'
                mapping_types:
                    enum: string
                options:
                    1002: "SET NAMES utf8"  #initial query
                    1000: true              #"PDO::MYSQL_ATTR_USE_BUFFERED_QUERY"
            subscription:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name_subscription%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
                server_version: '5.5'
                mapping_types:
                    enum: string
                options:
                    1002: "SET NAMES utf8"  #initial query
                    1000: true              #PDO::MYSQL_ATTR_USE_BUFFERED_QUERY
```
